// Generated by `graft add` — do not edit.
// MDX component map for @graft/sdk-next MdxBody. Safe to delete: `graft add`
// regenerates it from whatever PascalCase *.tsx files live in components/.
import type { MdxComponents } from "@graft/sdk-next";
import { Callout } from "./Callout";
import { Faq } from "./Faq";

export const mdxComponents: MdxComponents = {
  Callout,
  Faq,
};
