// Generated by `graft add` — do not edit.
// Aggregates the owned primitives under graft/ into merged collections/functions.
// Safe to delete: `graft add` regenerates it from whatever modules live in graft/.
import { mergePrimitives } from "@graft/core";

export const { collections, functions } = mergePrimitives([]);
