/**
 * The compat apps (compat/next15, compat/next16) are generated by
 * compat/write-apps.mjs and committed. CI's smoke runs whatever is committed,
 * so a pin edited in the generator but never regenerated would be tested at
 * its old version without anyone noticing. This fails instead.
 */
import { spawnSync } from "node:child_process";
import { resolve } from "node:path";
import { describe, expect, it } from "vitest";

const generator = resolve(import.meta.dirname, "../compat/write-apps.mjs");

describe("the committed compat apps", () => {
  it("match what compat/write-apps.mjs generates", () => {
    const result = spawnSync(process.execPath, [generator, "--check"], { encoding: "utf8" });
    expect(result.stderr).toBe("");
    expect(result.status).toBe(0);
  });
});
