/**
 * Generate the `graft/index.ts` barrel — the aggregation point `graft add`
 * regenerates on every add.
 *
 * It statically imports every primitive module under `graft/` and merges their
 * collections/functions via @usegraft/core's `mergePrimitives`, so the app bundler
 * (which imports graft.config.ts statically) and the CLI (jiti) see the SAME
 * merged config through one mechanism. This is generated infra — header-marked,
 * never hand-edited. (docs/design-notes/registry.md § Wiring.)
 */
const HEADER = [
  "// Generated by `graft add` — do not edit.",
  "// Aggregates the owned primitives under graft/ into merged collections/functions.",
  "// Safe to delete: `graft add` regenerates it from whatever modules live in graft/.",
];

/** A `graft/<basename>.ts` basename → a safe, camelCase JS identifier. */
export function moduleIdentifier(basename: string): string {
  const camel = basename.replace(/[^a-zA-Z0-9]+(.)?/g, (_all, next: string | undefined) =>
    next ? next.toUpperCase() : "",
  );
  return /^[a-zA-Z_$]/.test(camel) ? camel : `_${camel}`;
}

/** Barrel source for the given primitive module basenames (deduped + sorted). */
export function barrelSource(basenames: readonly string[]): string {
  const entries = [...new Set(basenames)]
    .sort()
    .map((base) => ({ base, id: moduleIdentifier(base) }));
  const imports = entries.map((e) => `import * as ${e.id} from "./${e.base}";`);
  const list = entries.map((e) => e.id).join(", ");
  return [
    ...HEADER,
    'import { mergePrimitives } from "@usegraft/core";',
    ...imports,
    "",
    `export const { collections, functions } = mergePrimitives([${list}]);`,
    "",
  ].join("\n");
}
