/**
 * Generate the `graft/index.ts` barrel — the aggregation point `graft add`
 * regenerates on every add.
 *
 * It statically imports every primitive module under `graft/` and merges their
 * collections/functions via @usegraft/core's `mergePrimitives`, so the app bundler
 * (which imports graft.config.ts statically) and the CLI (jiti) see the SAME
 * merged config through one mechanism. This is generated infra — header-marked,
 * never hand-edited. (docs/design-notes/registry.md § Wiring.)
 */
import { GraftError } from "@usegraft/contracts";

const HEADER = [
  "// Generated by `graft add` — do not edit.",
  "// Aggregates the owned primitives under graft/ into merged collections/functions.",
  "// Safe to delete: `graft add` regenerates it from whatever modules live in graft/.",
];

/** A `graft/<basename>.ts` basename → a safe, camelCase JS identifier. */
export function moduleIdentifier(basename: string): string {
  const camel = basename.replace(/[^a-zA-Z0-9]+(.)?/g, (_all, next: string | undefined) =>
    next ? next.toUpperCase() : "",
  );
  return /^[a-zA-Z_$]/.test(camel) ? camel : `_${camel}`;
}

/** Barrel source for the given primitive module basenames (deduped + sorted). */
export function barrelSource(basenames: readonly string[]): string {
  const entries = [...new Set(basenames)]
    .sort()
    .map((base) => ({ base, id: moduleIdentifier(base) }));

  // Distinct filenames can collapse onto one identifier — my-mod.ts and
  // myMod.ts both become `myMod` — which emitted two imports binding the same
  // name and made the regenerated barrel fail to compile. The file is
  // header-marked "do not edit", so a developer hitting this had no sanctioned
  // way out. Refuse with the names, rather than generating something broken.
  const byId = new Map<string, string[]>();
  for (const entry of entries) {
    byId.set(entry.id, [...(byId.get(entry.id) ?? []), entry.base]);
  }
  const collisions = [...byId.entries()].filter(([, files]) => files.length > 1);
  if (collisions.length > 0) {
    const described = collisions
      .map(([id, files]) => `${files.map((f) => `${f}.ts`).join(" and ")} both become "${id}"`)
      .join("; ");
    throw new GraftError({
      code: "REGISTRY_ITEM_INVALID",
      message: `Modules under graft/ collide when converted to identifiers: ${described}.`,
      fix: "Rename one of each colliding pair so their camelCase forms differ — graft/index.ts imports each module under that name, and two imports cannot share one binding.",
      details: { collisions: Object.fromEntries(collisions) },
    });
  }
  const imports = entries.map((e) => `import * as ${e.id} from "./${e.base}";`);
  const list = entries.map((e) => e.id).join(", ");
  return [
    ...HEADER,
    'import { mergePrimitives } from "@usegraft/core";',
    ...imports,
    "",
    `export const { collections, functions } = mergePrimitives([${list}]);`,
    "",
  ].join("\n");
}
