/**
 * Generate `components/mdx-components.ts` — the MDX component map that
 * `graft add` regenerates when block items land under components/.
 *
 * Parallel to the graft/ barrel: statically imports each PascalCase component
 * file and re-exports them as a map for `MdxBody`. Generated infra — header-
 * marked, never hand-edited. Basename = export name (`Callout.tsx` → `Callout`).
 */
const HEADER = [
  "// Generated by `graft add` — do not edit.",
  "// MDX component map for @usegraft/sdk-next MdxBody. Safe to delete: `graft add`",
  "// regenerates it from whatever PascalCase *.tsx files live in components/.",
];

/** `Callout.tsx` / `callout.tsx` → export identifier `Callout` (PascalCase). */
export function componentExportName(filename: string): string {
  const base = filename.replace(/\.tsx?$/, "");
  if (!base) return "Component";
  // Already PascalCase (or single segment): capitalize first letter only if needed.
  return base.charAt(0).toUpperCase() + base.slice(1);
}

/**
 * MDX map source for the given component basenames (no extension).
 * Empty list → empty map object (valid; pages render markdown-only MDX).
 */
export function mdxComponentsSource(basenames: readonly string[]): string {
  const entries = [...new Set(basenames)]
    .map((base) => {
      const fileBase = base.replace(/\.tsx?$/, "");
      return { fileBase, exportName: componentExportName(fileBase) };
    })
    .sort((a, b) => a.exportName.localeCompare(b.exportName));

  if (entries.length === 0) {
    return [
      ...HEADER,
      'import type { MdxComponents } from "@usegraft/sdk-next";',
      "",
      "export const mdxComponents: MdxComponents = {};",
      "",
    ].join("\n");
  }

  const imports = entries.map((e) => `import { ${e.exportName} } from "./${e.fileBase}";`);
  const props = entries.map((e) => `  ${e.exportName},`).join("\n");

  return [
    ...HEADER,
    'import type { MdxComponents } from "@usegraft/sdk-next";',
    ...imports,
    "",
    "export const mdxComponents: MdxComponents = {",
    props,
    "};",
    "",
  ].join("\n");
}
