// Generated by `graft add` — do not edit.
// Aggregates the owned primitives under graft/ into merged collections/functions.
// Safe to delete: `graft add` regenerates it from whatever modules live in graft/.
import { mergePrimitives } from "@usegraft/core";
import * as comments from "./comments";
import * as commerce from "./commerce";
import * as scopedAccess from "./scoped-access";

export const { collections, functions } = mergePrimitives([comments, commerce, scopedAccess]);
